logging:
  level:
    org.springframework.web: ERROR
    ru.skypro: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${user.home}/ads-reselling-platform/app.log