-- liquibase formatted sql

-- changeSet rickln: v1.0
CREATE TABLE IF NOT EXISTS USERS (
  USERNAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(68) NOT NULL,
  ENABLED  BOOL NOT NULL,
  PRIMARY KEY(USERNAME)
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
  USERNAME  VARCHAR(50) NOT NULL,
  AUTHORITY VARCHAR(68) NOT NULL,
  FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);
