CREATE TABLE USERS (
  USERNAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(68) NOT NULL,
  ENABLED  BOOL NOT NULL,
  PRIMARY KEY(USERNAME)
);

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES
  ('user@gmail.com',  '{bcrypt}$2a$10$1nbufsXoiJkKaiVTRwje5uaAdwnIO1Np4k8TITAUcHcSyqM2ZeyFS', true),
  ('admin@gmail.com', '{bcrypt}$2a$10$9mILML6CRCBAjcWd8XpUw.P9RCnkU2qyvhG4EQA6wvi4zpzpaVKKe', true);

CREATE TABLE AUTHORITIES (
  USERNAME  VARCHAR(50) NOT NULL,
  AUTHORITY VARCHAR(68) NOT NULL,
  FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

INSERT INTO AUTHORITIES VALUES
  ('user@gmail.com',  'ROLE_USER'),
  ('admin@gmail.com', 'ROLE_USER'),
  ('admin@gmail.com', 'ROLE_MANAGER');
